/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'appointment-add': RouteRecordInfo<'appointment-add', '/appointment/add', Record<never, never>, Record<never, never>>,
    'appointment-edit-id': RouteRecordInfo<'appointment-edit-id', '/appointment/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'appointment-list': RouteRecordInfo<'appointment-list', '/appointment/list', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'medical-record': RouteRecordInfo<'medical-record', '/medical-record', Record<never, never>, Record<never, never>>,
    'medical-record-calendar': RouteRecordInfo<'medical-record-calendar', '/medical-record/calendar', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'payments-list': RouteRecordInfo<'payments-list', '/payments/list', Record<never, never>, Record<never, never>>,
    'pet-add': RouteRecordInfo<'pet-add', '/pet/add', Record<never, never>, Record<never, never>>,
    'pet-edit-id': RouteRecordInfo<'pet-edit-id', '/pet/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pet-list': RouteRecordInfo<'pet-list', '/pet/list', Record<never, never>, Record<never, never>>,
    'roles-permisos': RouteRecordInfo<'roles-permisos', '/roles-permisos', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'staffs': RouteRecordInfo<'staffs', '/staffs', Record<never, never>, Record<never, never>>,
    'surgerie-add': RouteRecordInfo<'surgerie-add', '/surgerie/add', Record<never, never>, Record<never, never>>,
    'surgerie-edit-id': RouteRecordInfo<'surgerie-edit-id', '/surgerie/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surgerie-list': RouteRecordInfo<'surgerie-list', '/surgerie/list', Record<never, never>, Record<never, never>>,
    'vaccination-add': RouteRecordInfo<'vaccination-add', '/vaccination/add', Record<never, never>, Record<never, never>>,
    'vaccination-edit-id': RouteRecordInfo<'vaccination-edit-id', '/vaccination/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'vaccination-list': RouteRecordInfo<'vaccination-list', '/vaccination/list', Record<never, never>, Record<never, never>>,
    'veterinarie-add': RouteRecordInfo<'veterinarie-add', '/veterinarie/add', Record<never, never>, Record<never, never>>,
    'veterinarie-edit-id': RouteRecordInfo<'veterinarie-edit-id', '/veterinarie/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'veterinarie-list': RouteRecordInfo<'veterinarie-list', '/veterinarie/list', Record<never, never>, Record<never, never>>,
  }
}
